# SPDX-License-Identifier: GPL-2.0-only

CFLAGS += -D__EXPORTED_HEADERS__ -I$(top_srcdir)/include/uapi
CFLAGS += -Wall -Wextra -O2 $(KHDR_INCLUDES)

TEST_GEN_PROGS := edu_chat_test

include ../lib.mk
